In [5]:
import numpy as np

In [256]:
# class FNN:
#     def __init__(self, input_size=6, hidden_size=[8,8], output_size=1, 
#                  learning_rate=0.01, activation="RELU"):
        
#         self.lr=learning_rate
        
#         self.weights={}
#         self.weights['W1']=np.random.randn(input_size, hidden_size[0])
#         self.weights['W2']=np.random.randn(hidden_size[0], hidden_size[1])
#         self.weights['W3']=np.random.randn(hidden_size[1], output_size)
        
#         self.bias={}
#         self.bias['b1']=np.zeros(shape=(hidden_size[0],))
#         self.bias['b2']=np.zeros(shape=(hidden_size[1],))
#         self.bias['b3']=np.zeros(shape=(output_size))
        
#         self.activations=RELU()
        
#         if activation=="RELU":
#             self.activatons=RELU()
#         elif activation=="tanh":
#             self.activation=np.tanh()
        
#     def forward(self, input):
#         h1=np.matmul(input, self.weights['W1'])+ self.bias['b1']
#         h2=np.matmul(h1,self.weights['W2'])+ self.bias['b2']
#         h3=np.matmul(h2, self.weigths['W3']) + self.bias['b3']
        
#         return h3
    
# from tds    
class Layer:
    def __init__(self):
        """Here you can initialize layer parameters (if any) and auxiliary stuff."""
        # A dummy layer does nothing
        self.weights = np.zeros(shape=(input.shape[1], 10))
        bias = np.zeros(shape=(10,))
        pass
    
    def forward(self, input):
        """
        Takes input data of shape [batch, input_units], returns output data [batch, 10]
        """
        output = np.matmul(input, self.weights) + bias
        return output
    
class RELU(Layer):
    def __init__(self):
        pass
    
    def forward(self, z):
        return np.maximum(0,z)
    
    def backward(self, z, out_grad):
        relu_grad = z > 0
        return out_grad*relu_grad   
#         relu_grad=[]
#         for i in range(len(z)):
#             if z[i]>=0:
#                 relu_grad[i]=1
#             else:
#                 relu_grad[i]=0
#         return np.dot(np.transpose(out_grad),relu_grad)

class tanh:
    def __init__(self):
        pass
    
    def forward(self,z):
        return np.tanh(z)
    
    def backward(self, z, out_grad):
        return np.dot(np.transpose(out_grad),np.sinh(z))
    
class Hidden(Layer):
    def __init__(self, last_size, hidden_size, learning_rate=0.01,
                weight_init_std=0.01):
        self.W=weight_init_std * np.random.randn(last_size, hidden_size)
        self.b=np.zeros(shape=(hidden_size,))
        
        self.lr=learning_rate
        
    def forward(self, X): # forward X = result from last layer(or input)
        layer_out= np.dot(X, self.W) + self.b
        return layer_out
    
    def backward(self, x, grad_out): # x=input of data
        dW = np.dot(np.transpose(x), grad_out)
        db = np.sum(grad_out, axis=0)
#        dx = np.dot(np.transpose(grad_out), self.W)
        dx = np.dot(grad_out,np.transpose(self.W))
        
        self.W -= self.lr * dW
        self.b -= self.lr * db
        
        return dx
        

In [257]:
#loss function
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        
    # 教師データがone-hot-vectorの場合、正解ラベルのインデックスに変換
    if t.size == y.size:
        t = t.argmax(axis=1)
             
    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

def crossentropy_loss(y_pred, t_train):
    loss = cross_entropy_error(y_pred, t_train)
    return loss

def grad_crossentropy_loss(y_pred, t_train):
    batch_size=t_train.shape[0]
    dx=(y_pred-t_train)/batch_size
    return dx

In [197]:
y=np.array([[0.1,0.9,0],[0,0.1,0.9]])
t=np.array([[0,1,0],[0,0,1]])
crossentropy_loss(y, t)


0.1053604045467214

In [162]:
#Loss function
def softmax_crossentropy_with_logits(logits,reference_answers):
    #print(type(len(logits)))
    logits_for_answers = logits[np.arange(len(logits)),reference_answers]
    xentropy = - logits_for_answers + np.log(np.sum(np.exp(logits),axis=-1))
    return xentropy

def grad_softmax_crossentropy_with_logits(logits,reference_answers):
    """Compute crossentropy gradient from logits[batch,n_classes] and ids of correct answers"""
    ones_for_answers = np.zeros_like(logits)
    ones_for_answers[np.arange(len(logits)),reference_answers] = 1
    softmax = np.exp(logits) / np.exp(logits).sum(axis=-1,keepdims=True)
    return (- ones_for_answers + softmax) / logits.shape[0]

In [15]:
from mnist import load_mnist
(x_train, t_train),(x_test,t_test)= load_mnist(normalize=True, one_hot_label=True)

Done
Done
Done
Done
Converting train-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting train-labels-idx1-ubyte.gz to NumPy Array ...
Done
Converting t10k-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting t10k-labels-idx1-ubyte.gz to NumPy Array ...
Done
Creating pickle file ...
Done!


In [36]:
print(x_test.shape)

(10000, 784)


In [21]:
mnist_data=np.array([x_train,t_train,x_test,t_test])
mnist_data[1]
print(type(mnist_data[1]))

<class 'numpy.ndarray'>


In [37]:
for i in range(len(mnist_data)):
    print(mnist_data[i].shape)

(60000, 784)
(60000, 10)
(10000, 784)
(10000, 10)


In [104]:
for i in range(len(mnist_data)):
    print(mnist_data[i].shape)

(60000, 784)
(60000, 10)
(10000, 784)
(10000, 10)


In [260]:
import numpy as np

# input_size=6
# hidden_size=[8,8]
# output_size=1
# learning_rate=0.01


# network=[]
# network.append(Hidden(input_size, hidden_size[0], learning_rate=self.lr))
# network.append(Hidden(hidden_size[1], hidden_size[2], learning_rate=self.lr))

class FNN:
    def __init__(self, input_size=6, hidden_size=[8,8], output_size=1,
                 learning_rate=0.01
                 ): # list with all train/test data
        self.lr=learning_rate
        
#         self.X_train=data_input[0]
#         self.t_train=data_input[1]
#         self.X_test=data_input[2]
#         self.t_test=data_input[3]
        
        self.network=[]
        self.network.append(Hidden(input_size, hidden_size[0], learning_rate=self.lr))
        self.network.append(Hidden(hidden_size[0], hidden_size[1], learning_rate=self.lr))
        self.network.append(Hidden(hidden_size[1], output_size, learning_rate=self.lr))
        self.network.append(tanh())
        #self.network.append(RELU())
        
    def predict(self, x_train): 
        each_output = []
        X=x_train
    
        for i in range(len(self.network)):
            each_output.append(self.network[i].forward(X))
            X = self.network[i].forward(X)

        return each_output
    
    def train(self, X_train, t_train):
        activations = self.predict(X_train)
        for i in range(len(activations)):
            print(activations[i].shape)
            
        pred_y = activations[-1]
        print("y:"+str(pred_y.shape))
        print(pred_y[0])
        print("t:"+str(t_train.shape))
        print(t_train[0])
        
        loss = crossentropy_loss(pred_y, t_train)
        print("loss"+str(loss))
        loss_grad = grad_crossentropy_loss(pred_y, t_train)
        print("loss_grad"+str(loss_grad.shape)+"\n")
        #print(loss_grad)
        
        for i in range(1,len(self.network)):
            print(len(self.network) - i)
            print("network:"+str(self.network[len(self.network) - i]))
            loss_grad = self.network[len(self.network) - i].backward(activations[len(self.network) - i -1], loss_grad)
            print("x:"+str(activations[len(self.network) - i -1].shape))
            print("loss_grad:"+str(loss_grad.shape))
    
            
        return np.mean(loss)
    
    def acuuracy(self, X_test, t_test):
        results = self.forward(self.X_test)
        pred_ = results[-1]
        
        
        y = np.argmax(pred_, axis=1)
        if t_test.ndim!=1: 
            t_test=np.argmax(t_test, axis=1)
        score = np.sum(t_test==y)/float(y.shape[0])
        
        return score
        
    

In [261]:

train_loss_list=[]
train_acc_list=[]
test_acc_list=[]


iters_num=10000
batch_size=100
lr=0.1
train_size=x_train.shape[0]

network = FNN(input_size=784, hidden_size=[13,8], output_size=10,
                 learning_rate=lr)

for i in range(iters_num): #进行iters_num次计算
    #获取mini_batch
    batch_mask=np.random.choice(train_size,batch_size)
    x_batch=x_train[batch_mask]
    t_batch=t_train[batch_mask]
        
    loss=network.train(x_batch,t_batch)
    train_loss_list.append(loss)
    
    #计算每个epoch的精度
    if i%iter_per_epoch ==0:
        train_acc=network.accuracy(x_train,t_train)
        test_acc=network.accuracy(x_test, t_test)
        train_acc_list.append(train_acc)
        test_acc_list.append(test_acc)
        print("train acc, test acc | "+str(train_acc)+","+str(test_acc))

(100, 13)
(100, 8)
(100, 10)
(100, 10)
y:(100, 10)
[-1.93418277e-04  5.06786840e-05  7.38489238e-05  1.18017983e-04
  7.93939410e-05  1.04171472e-04  7.97418071e-05 -6.76114906e-05
  5.42271335e-05 -2.71349120e-05]
t:(100, 10)
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
lossnan
loss_grad(100, 10)

3
network:<__main__.tanh object at 0x000001CB6F2A7E88>
x:(100, 10)
loss_grad:(10, 10)
2
network:<__main__.Hidden object at 0x000001CB6F2A71C8>


C:\Users\yexue\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in log
  if sys.path[0] == '':


ValueError: shapes (8,100) and (10,10) not aligned: 100 (dim 1) != 10 (dim 0)

In [249]:
a=np.random.randn(2,3)
print(a>0)
print(a)
print(tanh().forward(a))

[[False False False]
 [ True  True  True]]
[[-1.98236587 -1.43953054 -1.15220995]
 [ 1.29089336  0.17021564  1.10872716]]
[[-0.9627603  -0.89360318 -0.81848486]
 [ 0.85936033  0.16859056  0.803612  ]]
